### ISSUE TITLE
Missing Micrometer Metrics and Tags After Updating to Axon Console 1.5.2

### ISSUE THREAD

**Issue by lachja** [AxonIQ/console-framework-client#77]
### Basic information
After updating from Axon Console version 1.5.1 to 1.5.2, I noticed a significant problem with missing metrics and tags in my Micrometer integration. Specifically, many standard metrics, such as JVM metrics, are no longer registered, and the remaining metrics no longer include the previously defined Micrometer tags.

* AxonIQ Console Framework Client version: 1.5.2
* JDK version:  17
* Axon Framework version: 4.10.0
* Complete executable reproducer: https://github.com/lachja/axon-micrometer-metrics-issue-demo

### Steps to reproduce

1. Clone the demo project from [this repository](https://github.com/lachja/axon-micrometer-metrics-issue-demo).
2. Run the application with Axon Console 1.5.1 and observe that all metrics and tags are present.
3. Update the Axon Console dependency to 1.5.2 and rerun the application.
4. Observe that several metrics are missing and custom tags are no longer applied.

### Expected behaviour

All metrics should be visible and tagged correctly, as they were in version 1.5.1.

### Actual behaviour

Metrics are missing, and custom tags are not applied in version 1.5.2.

**Comment by CodeDrivenMitch** [comment]
Thank you for letting us know, @lachja! I will dive into it and come back with a fix as soon as possible.

**Comment by CodeDrivenMitch** [comment]
@lachja Release 1.7.2 with the fix for this is available in Maven Central

**Comment by lachja** [comment]
Thank you @CodeDrivenMitch. The problem no longer occurs with version 1.7.2.
